### ISSUE TITLE
Mavericks dependency not required

### ISSUE THREAD

**Issue by daniel-toman** [gmerlino/homebrew-exfat#1]
Thanks for this! I don't believe the OS version dependency on Mavericks is required. When I removed that line from the formula, it built just fine on Leopard with Tigerbrew (a PPC version of Homebrew).  

Here is the formula without the OS dependency. [exfat.rb.zip](https://github.com/gmerlino/homebrew-exfat/files/2169323/exfat.rb.zip)

Cheers,
Daniel

**Comment by gmerlino** [comment]
Thanks! Fixed :)
